### ISSUE TITLE
Issue with Facebook login

### ISSUE THREAD

**Issue by Anonvide** [DemocracyOS/app#1067]
its something with the app config. The redirect callback url is passed from app side. why does the redirect to fb param have server ip instead of domain?

**Comment by slifszyc** [comment]
can you be more specific please? which branch are you working on?

**Comment by Anonvide** [comment]
Its the master branch. Please see the facebook login of the deployment: http://publicitors.com/signin. The redirect_uri param is ip instead of host.

**Comment by mjlescano** [comment]
Did you set the `HOST` configuration to `publicitors.com`?

**Comment by Anonvide** [comment]
Hosts file has the config as: 
162.208.10.46 www.publicitors.com www

**Comment by mjlescano** [comment]
@Anonvide I was meaning the `host` configuration option of the app. You can set it via the environment variable `HOST` or setting it on your `config/production.json`.

e.g.: in your `config/production.json`:
```json
{
  "host": "publicitors.com"
}
```

**Comment by Anonvide** [comment]
Hello guys! 

Host was set as ip instead of publicitors.com. I have changed it, but it doesn't work...

I still get this message: "The URL provided is not authorized by the application configuration: one or more URLs provided are not allowed by the application settings. It (they) mus  match with the url of the site or Canvas, or domain should be a subdomain of one of the fields of application".

**Comment by mjlescano** [comment]
@Anonvide awesome :). That error is because you have to add your domain to the Facebook application Settings, as pointed out on point `3` of this wiki page: https://github.com/DemocracyOS/app/wiki/Facebook-Signin-Signup

If that doesn't work, let's continue the conversation at the DemocracyOS's [Gitter Room](https://gitter.im/DemocracyOS/app), we use Github issues for bug reports and feature request.
