### ISSUE TITLE
Add a fallback language

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#337]
When no translation is found in the locale the app is running, then there should be a fallback language (en) to translate it.

**Comment by s01us** [comment]
Yes, and it's sometimes great to have some basic fallback hardcoded. 
e.g. zh-HK (chinese, hong-kong) can fallback to zh-TW (chinese, traditional, taiwan), and if a translation is missing there, fallback to the default. 

*[ important but not urgent! ]*
I've got a question about how reliable browser locale is. I've built a thing which will display major locales in browser at the [bottom of this page](https://www.loomio.org/translation) ... but I think it would also be great to do a comparison of geolocation with locales detectedin browser. Have you looked at that data ?

**Comment by gvilarino** [comment]
Yeah, browser loacale isn't super-trustworthy; I guess you can think it may be ok but if not you just fall back to a default. I've found geo-ip more of a problem than of a solution since it usually takes a bit of time to resolve location and it's no guarantee of what the user preferences are (in places like Spain, for instance).

**Comment by mjlescano** [comment]
Closed by #835
