### ISSUE TITLE
Emancipate from MongoHQ

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#525]
As of sometime earlier this week, MongoHQ (now Compose Mongo) no longer has a free tier. Current deployments are unaltered and remain free (I don't know for how long, we should investigate), but new ones can't be made free. The quick alternative is MongoLab's free tier.

For this we need to make `env.js` not dependant of the `MONGOHQ_URL` env variable but instead from a generic `MONGO_URI`; and handle any alias internally as part of the config logic.

We should communicate this as part of the 0.9 release as well.

**Comment by tarasdudar** [comment]
@gvilarino,

I've just noticed this problem trying to deploy 0.9 release in a new app on heroku. I'm assuming it has not been resolved yet since the ticket is still open. I just wanted to confirm that my only option at the moment is to buy the service from MongoHQ and wait until you get the MongoLab supported.

Is there any other option?

**Comment by gvilarino** [comment]
@tarasdudar yeah, it isn't live yet but for a local quickfix it's pretty simple; just change any reference to `MONGOHQ_URL` to `MONGO_URI` in `env.js` or `config/production.json` and you should be good to go.

Also, double check your `notifier` instance to hit the same endpoint.
