### ISSUE TITLE
need to add "Contact Us" page and bug tracking capability to democracyOS

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#563]
I've been working on this for Ukrainian version of democracyOS and I've just realized it should probably be included in the main code.

We are building the tool for voting and collaboration on creating new laws. The collaboration implies the ability for each citizen to submit their new law proposals, new clauses for existing laws, their own editions and corrections to each law. In each case all the requests from the citizens would need to be evaluated by someone with admin privileges and put for voting if applicable. The best way to handle all of these requests would be through some kind of a tracking system engine. The citizens would submit all of their requests into the tracking system as tickets and then they would be dis-positioned by the admin. That way multiple admin people could work on multiple requests at the same time and everything would be tracked appropriately. Everyone should have the access to the tracking system page to see what is going on with all the tickets.

To enable this feature I went ahead and changed the description for the "Learn More" url in the centre of the page to the following.

"If you would like to propose for voting your addition, change or correction to the below law please click here".

I then started to work on a separate web page to handle all of these requests but I now think it would be a lot more powerful if all of these are handled inside the app itself.

Collaboration would also imply the ability for the citizens to provide the feedback and suggestions to the app admin. "Contact Us" page could be such a tool. It could also be combined with tracking tool.

All of these seams too obvious and I'm wondering if this capability already exist and I just need to enable it somehow. Please let me know if this is the case.

**Comment by gvilarino** [comment]
I agree that those things are usually needed in a production environment, but usually they are intended as very customised for the organisation/community implementing DOS; that's why we provide the basic building blocks and leave the rest to implementors.

Basic blocks would be:

* The `LEARN_MORE` env var: splashes the yellow thingie on top of every page with a link.
* The `ORGANIZATION_NAME` and `ORGANIZATION_URL` that become the link on the top right of the header (next to the `signin` link). This can be easily replicated by adding another div to the header.
* The `feedback` component; it's all up and ready for you to set up [Uservoice](https://www.uservoice.com/) as a feedback/helpdesk platform.

Then it's sort of up to you.

On the other hand, we're currently working on a way for distributed collaboration can happen; we will be launching this sometime during the next 3 months.

@tarasdudar does this help? If so, let me know so I can close this issue.
