### ISSUE TITLE
Update language files handling

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#630]
Right now, all language files are copied to `pubic/app.js` during the build.

This means all language files are included in the `app.js` file that is sent to the client. The bigger the language file gets, the bigger the client gets, but exponentially in this last case.

We should find a proper approach for this. A quick delivery boost may be attained through #633, but that won't do for a final solution

**Comment by gvilarino** [comment]
The way I see it, there are two possible solutions:

1. The build process should copy all language files should `/public` and sent to the client separately from `app.js`, based on the user's locale.
2. The build process should include only the language selected by `LOCALE` during build.

Approach 1 would user language to be de-coupled from the server's (which would in turn become the 'default' locale instead of the only locale). This would imply adding a `locale` attribute to `user` so users may select their desired locale. If we do this, I'd suggest we set this on user creation, based on user's browser locale if available, to backend default locale otherwise. Also, language selection should be made available in the user preferences section.

Approach 2 would be quicker but would only provide a temporal solution to what we should, in the end, provide (similar to what I suggest in 1)

**Comment by jfresco** [comment]
I think approach 1 is a nice improvement. Would be great to have that feature.

**Comment by slifszyc** [comment]
For what we have now, I think 2 is a better approach.

We should rethink the translations before approach 1

**Comment by tarasdudar** [comment]
Just a comment on this topic. There are some multilanguage countries where it is common to discuss the same topics simultaneuosly in different languages by different people. For example a news website would have the same articles translated in different languages and users would have access to exactly the same content of the website with only difference being language based on their LOCALE preferences. The discussion forum under the article would not be translated and all the users would see the comments in original languages independent of their LOCALE settings. 

I had a similar use case for DOS in mind. Ideally would be nice to have the same deployment supporting multiple languages. Approach 1 would work perfect for this.

**Comment by gvilarino** [comment]
I agree: in the ideal scenario it should be possible to provide a `law` in multiple languages (i.e.: like wikipedia for its articles). I guess this feature should come after proposed solutions 1 or 2

**Comment by jfresco** [comment]
So, this is the strategy we thought:
- [x] On build, generate one `app.js` per translation file (i.e., `app.en.js`, `app.it.js`, etc)
- [ ] On server side, infer the locale of the current user (settings or user-agent or `'en'`).
- [ ] On client side only require the `app.[locale].js` file that corresponds to the user's locale.
