### ISSUE TITLE
Prevent logged in users from visiting /signin or /signup

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#676]
Should redirect to home or something like that.

**Comment by ben-pr-p** [comment]
I wrote a function invertedRestrict that was similar to the function restrict in lib/utils that would redirect to home if the user was logged in.

Then I called it inside app.get('/signin', invertedRestrict, require('lib/layout') on line 11 of lib/signin/index.js. However, it seems that, according to the log in terminal, the token is deciphered after that line is run, so that the line always thinks that no one has logged in. I tried calling the function in a few other places including lib/boot/index.js's route to signin, but that prevented a user from actually signing in instead of taking them to the signing page.

Is this the right approach? What code/documentation should I be looking at to understand why the page is rendered before the token is deciphered?

**Comment by mjlescano** [comment]
Hi @ben-pr-p, thanks for the help!

That's because you're trying to do the redirect on the backend side, and we are handling the routes on frontend (in this case, at `/lib/signin/signin.js`). You should add a middleware on that route.

For example, we are using `citizen.required` here: https://github.com/DemocracyOS/app/blob/a7b3e7702393f610ba569b4ab0e8c179249051cc/lib/signup/signup.js#L50

You should add something like `citizen.restricted` and add it to `signin.js`.
